FROM registry.fedoraproject.org/fedora:latest

USER root

# ensure home exists and is writable
RUN mkdir -p $HOME

# Install ripgrep (required for opencode)
RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz \
 && tar -xzf ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz

ARG NODE_VERSION=24

RUN dnf install -y git nodejs$NODE_VERSION

# set npm prefix to avoid permission issues
RUN npm config set prefix "$HOME/.npm-global"
ENV PATH="$HOME/.npm-global/bin:$PATH"

# Install Opencode
# RUN curl -fsSL https://opencode.ai/install | bash
RUN /usr/local/bin/opencode --version

# Install the ACP proxy server
RUN npm install -g @rebornix/stdio-to-ws

ENV HOME=/home
# ensure home exists and is writable
RUN chown -R 65532:65532 $HOME && chmod -R u+rwx $HOME

USER 65532

ENTRYPOINT ["/usr/local/bin/stdio-to-ws"]
CMD ["--no-auth", "/usr/local/bin/opencode acp", "--port", "4000"]

