FROM registry.fedoraproject.org/fedora:latest

# Install ripgrep (required for opencode)
RUN curl -LO https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz \
 && tar -xzf ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz

ARG NODE_VERSION=24

RUN dnf install -y git nodejs$NODE_VERSION

ENV npm_config_store_dir=/tmp/.pnpm

# Install Opencode
RUN curl -fsSL https://opencode.ai/install | bash
RUN /root/.opencode/bin/opencode --version

# Install the ACP proxy server
RUN npm install -g @rebornix/stdio-to-ws

ENV HOME=/home

ENTRYPOINT ["/usr/local/bin/stdio-to-ws"]
CMD ["--no-auth", "/root/.opencode/bin/opencode acp", "--port", "4000"]

